package io.github.soleworks.validity

internal object Messages {
    const val REQUIRED: String = "is required"
    const val EQUAL_TO: String = "must be equal to {other}"
    const val NOT_EQUAL_TO: String = "must not be equal to {other}"
    const val ONE_OF: String = "must be one of {values}"
    const val NONE_OF: String = "must not be one of {values}"

    const val MIN: String = "must be at least {min}"
    const val MAX: String = "must be at most {max}"
    const val GREATER_THAN: String = "must be greater than {other}"
    const val LESS_THAN: String = "must be less than {other}"
    const val BETWEEN: String = "must be between {min} and {max}"

    const val MIN_LENGTH: String = "must have at least {min} characters"
    const val MAX_LENGTH: String = "must have at most {max} characters"
    const val LENGTH: String = "must have exactly {length} characters"
    const val LENGTH_BETWEEN: String = "must have between {min} and {max} characters"
    const val NOT_EMPTY: String = "must not be empty"
    const val NOT_BLANK: String = "must not be blank"
    const val MATCHES: String = "must match {regex}"
    const val NOT_MATCHES: String = "must not match {regex}"
    const val CONTAINS: String = "must contain {text}"
    const val NOT_CONTAINS: String = "must not contain {text}"
    const val STARTS_WITH: String = "must start with {prefix}"
    const val NOT_STARTS_WITH: String = "must not start with {prefix}"
    const val ENDS_WITH: String = "must end with {suffix}"
    const val NOT_ENDS_WITH: String = "must not end with {suffix}"
    const val UPPERCASE: String = "must be uppercase"
    const val LOWERCASE: String = "must be lowercase"
    const val LETTERS: String = "must contain only letters"
    const val DIGITS: String = "must contain only digits"
    const val LETTERS_OR_DIGITS: String = "must contain only letters or digits"
    const val ASCII: String = "must contain only ASCII characters"

    const val POSITIVE: String = "must be positive"
    const val NEGATIVE: String = "must be negative"
    const val POSITIVE_OR_ZERO: String = "must be positive or zero"
    const val NEGATIVE_OR_ZERO: String = "must be negative or zero"
    const val MULTIPLE_OF: String = "must be a multiple of {factor}"
    const val FINITE: String = "must be finite"
    const val MAX_DECIMAL_PLACES: String = "must have at most {max} decimal places"
    const val MAX_INTEGER_DIGITS: String = "must have at most {max} integer digits"

    const val PAST: String = "must be in the past"
    const val FUTURE: String = "must be in the future"
    const val PAST_OR_PRESENT: String = "must be in the past or present"
    const val FUTURE_OR_PRESENT: String = "must be in the future or present"
    const val AFTER: String = "must be after {other}"
    const val BEFORE: String = "must be before {other}"
    const val AFTER_OR_EQUAL: String = "must be after or equal to {other}"
    const val BEFORE_OR_EQUAL: String = "must be before or equal to {other}"
    const val BETWEEN_DATES: String = "must be between {start} and {end}"

    const val MIN_SIZE: String = "must have at least {min} items"
    const val MAX_SIZE: String = "must have at most {max} items"
    const val SIZE: String = "must have exactly {size} items"
    const val SIZE_BETWEEN: String = "must have between {min} and {max} items"
    const val DISTINCT: String = "must not contain duplicates"
    const val CONTAINS_ELEMENT: String = "must contain {element}"
    const val CONTAINS_ALL: String = "must contain all of {elements}"
    const val CONTAINS_ANY: String = "must contain any of {elements}"

    const val MIN_ENTRIES: String = "must have at least {min} entries"
    const val MAX_ENTRIES: String = "must have at most {max} entries"
    const val ENTRIES: String = "must have exactly {size} entries"
    const val ENTRIES_BETWEEN: String = "must have between {min} and {max} entries"
    const val CONTAINS_KEY: String = "must contain the key {key}"
    const val CONTAINS_KEYS: String = "must contain the keys {keys}"
}
